{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-reviewer.fullname" . }}
  labels:
    {{- include "gitlab-reviewer.labels" . | nindent 4 }}
type: Opaque
stringData:
  gitlab-token: {{ .Values.secrets.gitlabToken | quote }}
  webhook-secret: {{ .Values.secrets.webhookSecret | quote }}
{{- end }}
